# Generated by Django 4.2.6 on 2024-04-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='technician',
        ),
    ]
