# Generated by Django 5.0.1 on 2024-02-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_workorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='user',
        ),
    ]
