version: 0.1

environment_variables:
    plaintext:
        DJANGO_SETTINGS_MODULE: config.settings.test
        SECRET_KEY: django-insecure-y_*hy#i!@h95^&-s7#=4(26l6wpno)!1un_ah+l69xb9+w+&(b
        OPBEAT_ENABLED: False

phases:
    pre_build:
        commands:
            - echo Prebuild ops
            - pip3 install -r requirements.txt
    build:
        commands:
            - echo Building the application
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - "**/*"
