# Generated by Django 4.2.6 on 2024-04-01 13:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Flota',
                'verbose_name_plural': 'Disponibilidad de Flota',
            },
            managers=[
                ('disponibilidad', django.db.models.manager.Manager()),
            ],
        ),
    ]
