# Generated by Django 4.2.6 on 2024-04-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_prueba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prueba',
            options={'verbose_name': 'Prueba', 'verbose_name_plural': 'Prueba'},
        ),
    ]
