# Generated by Django 4.2.6 on 2024-04-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_prueba_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='disponibilidadflota',
            managers=[
            ],
        ),
    ]
