# Generated by Django 4.2.6 on 2024-04-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_disponibilidadflota_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisponibilidadFlota',
        ),
    ]
