# Generated by Django 4.2.6 on 2024-04-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_delete_disponibilidadflota'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Flota',
                'verbose_name_plural': 'Disponibilidad de Flota',
            },
        ),
    ]
