# Generated by Django 4.2.6 on 2024-04-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_disponibilidadflota'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadflota',
            name='bus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadflota',
            name='dias_fs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadflota',
            name='dias_operativos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadflota',
            name='disponibilidad',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadflota',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadflota',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadflota',
            name='serie',
            field=models.CharField(blank=True, choices=[('Queltehue', 'Queltehue'), ('Queltehue-Q2', 'Queltehue-Q2'), ('Tricahue', 'Tricahue'), ('Retrofit', 'Retrofit')], max_length=50, null=True),
        ),
    ]
