# Generated by Django 5.1.2 on 2024-10-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0042_alter_anualenergy_options'),
        ('reports', '0008_matrizkmflotahistorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrizkmflotahistorico',
            name='año',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matrizkmflotahistorico',
            name='bus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bus_signals.bus'),
        ),
        migrations.AlterField(
            model_name='matrizkmflotahistorico',
            name='dia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matrizkmflotahistorico',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
