# Generated by Django 5.1.2 on 2024-10-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_matrizkmflotahistorico_año_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatrizKmFlotaHistorico',
        ),
    ]
