# Generated by Django 5.1.2 on 2024-10-21 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0043_bus_lts_charge_bitacoracarga'),
        ('reports', '0012_matrizenergiaflotahistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMatrizKmAutoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('max_odometer', models.IntegerField(blank=True, null=True)),
                ('bus', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bus_signals.bus')),
            ],
        ),
    ]
