# Generated by Django 5.1.2 on 2024-10-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_dailymatrizkmautoreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatrizKmFlotaHistorico',
        ),
    ]
