# Generated by Django 5.1.2 on 2024-10-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_delete_matrizkmflotahistorico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymatrizkmautoreport',
            options={'verbose_name': 'Informe Historico Energia Flota Diario', 'verbose_name_plural': 'Informes Historico Energia Flota Diario'},
        ),
    ]
