# Generated by Django 5.0.1 on 2024-01-18 18:14

import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('job', models.CharField(choices=[('1', 'Electro Mecanico'), ('2', 'Electrico'), ('3', 'Electronico')], max_length=100, verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Technician',
                'verbose_name_plural': 'Technicians',
                'ordering': ['name'],
            },
            managers=[
                ('technician', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
