# Generated by Django 5.0.1 on 2024-01-23 11:27

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0002_technician_alter_bus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_mayor', models.CharField(blank=True, max_length=5, null=True, verbose_name='Mayor')),
                ('mark_minor', models.CharField(blank=True, max_length=5, null=True, verbose_name='Minor')),
                ('mark_patch', models.CharField(blank=True, max_length=5, null=True, verbose_name='Patch')),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
            },
            managers=[
                ('mark', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='jarvisversion',
            options={'verbose_name': 'Jarvis Version', 'verbose_name_plural': 'Jarvis Versions'},
        ),
        migrations.RemoveField(
            model_name='jarvisversion',
            name='TimeStamp',
        ),
        migrations.RemoveField(
            model_name='jarvisversion',
            name='bus',
        ),
        migrations.AddField(
            model_name='bus',
            name='jarvis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_signals.jarvisversion'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='lts_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='LTS Update'),
        ),
        migrations.AlterField(
            model_name='jarvisversion',
            name='jarvis_version_mayor',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Mayor'),
        ),
        migrations.AlterField(
            model_name='jarvisversion',
            name='jarvis_version_minor',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Minor'),
        ),
        migrations.AlterField(
            model_name='jarvisversion',
            name='jarvis_version_patch',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Patch'),
        ),
        migrations.AddField(
            model_name='bus',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_signals.mark'),
        ),
        migrations.DeleteModel(
            name='MarkVersion',
        ),
    ]
