# Generated by Django 5.0.1 on 2024-01-30 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0002_awspathbucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='awspathbucket',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_signals.bus'),
        ),
    ]
