# Generated by Django 5.0.1 on 2024-01-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0003_awspathbucket_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fusimessage',
            name='fusi_code',
            field=models.CharField(max_length=10, verbose_name='Fusi Code'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='job',
            field=models.CharField(choices=[('Electro Mecanico', 'Electro Mecanico'), ('Electrico', 'Electrico'), ('Electronico', 'Electronico')], max_length=100, verbose_name='Job'),
        ),
    ]
