# Generated by Django 5.0.1 on 2024-01-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0004_alter_bus_client_alter_bus_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='client',
            field=models.CharField(default='Link', max_length=20, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='plate_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Plate Number'),
        ),
    ]
