# Generated by Django 5.0.1 on 2024-02-01 20:45

import pytz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0004_alter_fusimessage_fusi_code_alter_technician_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awspathbucket',
            name='path_internal_date',
            field=models.DateTimeField(blank=True, default=pytz.timezone, editable=False, null=True, verbose_name='Path Date'),
        ),
        migrations.AlterField(
            model_name='awspathbucket',
            name='path_reveal_date',
            field=models.DateTimeField(blank=True, default=pytz.timezone, editable=False, null=True, verbose_name='Path Date'),
        ),
    ]
