# Generated by Django 5.0.1 on 2024-02-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0005_alter_awspathbucket_path_internal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awspathbucket',
            name='path_internal_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Path Internal Date'),
        ),
        migrations.AlterField(
            model_name='awspathbucket',
            name='path_reveal_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Path Reveal Date'),
        ),
    ]
