# Generated by Django 5.0.1 on 2024-01-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0006_alter_bus_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='lts_24_volt',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='LTS 24 Volt'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='lts_fusi',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='LTS FUSI'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='lts_isolation',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='LTS Isolation'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='lts_odometer',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='LTS Odometer'),
        ),
    ]
