# Generated by Django 5.0.1 on 2024-02-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0007_delete_profile_alter_fusimessage_fusi_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_ecu',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2')], max_length=20, null=True, verbose_name='Bus ECU'),
        ),
    ]
