# Generated by Django 5.0.1 on 2024-01-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0007_alter_bus_lts_24_volt_alter_bus_lts_fusi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='jarvis',
            field=models.CharField(blank=True, default='1.0.0', max_length=20, null=True, verbose_name='Jarvis'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='mark',
            field=models.CharField(blank=True, default='1.0.0', max_length=20, null=True, verbose_name='Mark'),
        ),
        migrations.AddField(
            model_name='bus',
            name='vision',
            field=models.CharField(blank=True, default='1.0.0', max_length=20, null=True, verbose_name='Vision'),
        ),
        migrations.DeleteModel(
            name='JarvisVersion',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
