# Generated by Django 5.0.1 on 2024-01-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0008_alter_bus_jarvis_alter_bus_mark_bus_vision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fusimessage',
            name='message_class',
            field=models.CharField(blank=True, choices=[('1', 'Q1'), ('2', 'Q2')], max_length=20, null=True, verbose_name='Message Class'),
        ),
    ]
