# Generated by Django 4.2.6 on 2024-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0009_alter_fusicode_fusi_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_series',
            field=models.CharField(choices=[('Queltehue', 'Queltehue'), ('Queltehue-Q2', 'Queltehue-Q2'), ('Tricahue', 'Tricahue'), ('Retrofit', 'Retrofit')], max_length=20, verbose_name='Serie'),
        ),
    ]
