# Generated by Django 5.0.1 on 2024-01-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0010_remove_fusimessage_fusi_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_img',
            field=models.ImageField(blank=True, default='bus.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_series',
            field=models.CharField(choices=[('Queltehue', 'Queltehue'), ('Tricahue', 'Tricahue'), ('Retrofit', 'Retrofit')], max_length=10, verbose_name='Serie'),
        ),
    ]
