# Generated by Django 4.2.6 on 2024-03-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0010_alter_bus_bus_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soc',
            name='soc_value',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='SOC Value'),
        ),
    ]
