# Generated by Django 4.2.6 on 2024-03-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0011_alter_soc_soc_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soc',
            name='soc_value',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='SOC Value'),
        ),
    ]
