# Generated by Django 4.2.6 on 2024-03-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0012_alter_soc_soc_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odometer',
            name='odometer_value',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Odometer Value'),
        ),
    ]
