# Generated by Django 4.2.6 on 2024-03-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        
        ('bus_signals', '0014_alter_odometer_odometer_value'),
    ]

  
