# Generated by Django 4.2.6 on 2024-03-25 15:18

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0015_delete_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('job', models.CharField(choices=[('Electro Mecanico', 'Electro Mecanico'), ('Electrico', 'Electrico'), ('Electronico', 'Electronico')], max_length=100, verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Technician',
                'verbose_name_plural': 'Technicians',
                'ordering': ['name'],
            },
            managers=[
                ('technician', django.db.models.manager.Manager()),
            ],
        ),
    ]
