# Generated by Django 4.2.6 on 2024-04-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0016_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fusicode',
            name='fusi_code',
            field=models.IntegerField(),
        ),
    ]
