# Generated by Django 4.2.6 on 2024-04-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0018_alter_bus_lts_fusi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='lts_odometer',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='LTS Odometer'),
        ),
        migrations.AlterField(
            model_name='odometer',
            name='odometer_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Odometer Value'),
        ),
    ]
