# Generated by Django 4.2.6 on 2024-04-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0020_alter_soc_soc_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='lts_soc',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='LTS SOC'),
        ),
    ]
