# Generated by Django 4.2.6 on 2024-04-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0023_alter_fusimessage_fusi_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_series',
            field=models.CharField(choices=[('Queltehue', 'Queltehue'), ('Queltehue-Q2', 'Queltehue-Q2'), ('Tricahue', 'Tricahue'), ('Retrofit', 'Retrofit')], max_length=30, verbose_name='Serie'),
        ),
    ]
