# Generated by Django 4.2.6 on 2024-04-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_workorder_technician'),
        ('bus_signals', '0024_alter_bus_bus_name_alter_bus_bus_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstate',
            name='bus',
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
        migrations.DeleteModel(
            name='BusState',
        ),
    ]
