# Generated by Django 4.2.6 on 2024-04-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0025_remove_busstate_bus_delete_technician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batteryhealth',
            name='battery_health_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Battery Health'),
        ),
    ]
