# Generated by Django 4.2.6 on 2024-04-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0027_chargestatus_soc_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='charging',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Charging'),
        ),
    ]
