# Generated by Django 4.2.6 on 2024-05-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0028_bus_charging'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='soh',
            field=models.IntegerField(blank=True, null=True, verbose_name='SOH'),
        ),
    ]
