# Generated by Django 4.2.6 on 2024-05-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0029_bus_soh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_series',
            field=models.CharField(choices=[('Queltehue', 'Queltehue'), ('Queltehue-Q2', 'Queltehue-Q2'), ('Tricahue', 'Tricahue'), ('Retrofit', 'Retrofit'), ('Prueba', 'Prueba')], max_length=100, verbose_name='Serie'),
        ),
    ]
