# Generated by Django 4.2.6 on 2024-05-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0030_alter_bus_bus_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='lts_isolation',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='LTS Isolation'),
        ),
    ]
