# Generated by Django 4.2.6 on 2024-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0032_bus_bus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='key_state',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Key State'),
        ),
    ]
