# Generated by Django 4.2.6 on 2024-06-06 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0033_bus_key_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='HvilStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(blank=True, null=True, verbose_name='TimeStamp')),
                ('hvil_status_value', models.IntegerField(blank=True, verbose_name='HVIL Status Value')),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_signals.bus')),
            ],
            options={
                'verbose_name': 'HVIL Status',
                'verbose_name_plural': 'HVIL Status',
                'ordering': ['TimeStamp'],
            },
            managers=[
                ('hvil_status', django.db.models.manager.Manager()),
            ],
        ),
    ]
