# Generated by Django 4.2.6 on 2024-07-25 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0034_hvilstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcuState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp')),
                ('lts_kms', models.IntegerField(blank=True, null=True, verbose_name='LTS Kms')),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_signals.bus')),
            ],
            options={
                'verbose_name': 'ECU State',
                'verbose_name_plural': 'ECU States',
            },
            managers=[
                ('ecu_state', django.db.models.manager.Manager()),
            ],
        ),
    ]
