# Generated by Django 4.2.6 on 2024-07-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0035_ecustate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecustate',
            name='sleep_state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
