# Generated by Django 4.2.6 on 2024-07-31 21:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0036_ecustate_sleep_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellsVoltage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(blank=True, null=True, verbose_name='TimeStamp')),
                ('max_v', models.FloatField(blank=True, null=True, verbose_name='Max')),
                ('min_v', models.FloatField(blank=True, null=True, verbose_name='Min')),
                ('avg', models.FloatField(blank=True, null=True, verbose_name='Avg')),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_signals.bus')),
            ],
            options={
                'verbose_name': 'Cells Voltage',
                'verbose_name_plural': 'Cells Voltage',
            },
            managers=[
                ('cells_voltage', django.db.models.manager.Manager()),
            ],
        ),
    ]
