# Generated by Django 4.2.6 on 2024-08-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0037_cellsvoltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellsvoltage',
            name='diff_max_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Diff Max Avg'),
        ),
        migrations.AddField(
            model_name='cellsvoltage',
            name='diff_min_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='Diff Min Avg'),
        ),
        migrations.AddField(
            model_name='cellsvoltage',
            name='diff_min_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Diff Min Max'),
        ),
    ]
