# Generated by Django 4.2.6 on 2024-08-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0038_cellsvoltage_diff_max_avg_cellsvoltage_diff_min_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='ecu_state',
            field=models.IntegerField(blank=True, null=True, verbose_name='ECU State'),
        ),
    ]
