# Generated by Django 5.1.2 on 2024-10-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0041_anualenergy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anualenergy',
            options={'ordering': ['-fecha']},
        ),
    ]
