# Generated by Django 5.1.2 on 2024-10-18 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_signals', '0042_alter_anualenergy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='lts_charge',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='BitacoraCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(blank=True, null=True, verbose_name='TimeStamp')),
                ('cycle_value', models.IntegerField(blank=True, null=True, verbose_name='Clycle Value')),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_signals.bus')),
            ],
        ),
    ]
