# Generated by Django 5.1.2 on 2024-11-25 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus_signals', '0043_bus_lts_charge_bitacoracarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('turno', models.CharField(choices=[('turno-a', 'Turno A'), ('turno-b', 'Turno B'), ('turno-c', 'Turno C'), ('fs', 'FS')], max_length=50)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_signals.bus')),
            ],
        ),
    ]
